#!/bin/bash


instances=(
"Crazy Frog"
"Easter Bunny"
"Kewpie"
"Miss Cleo"
"Mr. Clean" # 000
"Pink Panther"
"Agent Smith"
"Ernest P. Worrell"
"Advertising"
"Automobile" # 001
"Felix the Cat"
"Michelin Man"
"Morpheus"
"Big Boy Restaurants"
"Hello Kitty" #002
"Alfred E. Neuman"
"Skipper"
"Strawberry Shortcake"
"Bozo the Clown"
"Bugs Bunny" # 003
"Betty Crocker"
"Kermit the Frog"
"Mac Tonight"
"Mario"
"Ronald McDonald" # 004
"Minions"
"Mickey"
"Mr. Peanut"
"Pikachu"
"Pillsbury Doughboy" #005
"Scooby-Doo"
"Sonic the Hedgehog"
"Spirit of Ecstasy"
"SpongeBob"   
"Wendy Thomas" # 006
"Tinker Bell"
"Woody Woodpecker"
"Easter egg"
"Aunt Jemima"
"Barbie" # 007 
"Nancy Green"
"Playboy Bunny"
"Food"
"Chef Boyardee"
"Willy Wonka" # 008
"Billy the Puppet"
"Donald Duck"
"Fred Flintstone"
"Ken"
"Leo the Lion" # 009 
"Lucky Charms"
"Marlboro Man"
"Max Headroom"
"The Most Interesting Man in the World"
"The Noid" # 010
"Eddie"
"Public service announcement"
"Smokey Bear"
"Mascot"
"Mass media"
"History of advertising"
"Cola wars"
"Email spam"
"Fear of missing out"
"Guerrilla marketing"
"Social media marketing"
"A minor"
"A.E.I.O.U."
"A7V"
"Snoh Aalegra"
"Aaliyah"
"Aam Aadmi Party"
"Aardman Animations"
"Animation"
"Casper the Friendly Ghost"
"Daffy Duck"
"Garfield"
"Godzilla"
"Gollum"
"King Kong"
"Jimmy Neutron"
"Oswald the Lucky Rabbit"
"Popeye"
"Salad Fingers"
"Batgirl"
"Huntress"
"Betty Boop"
"Daphne Blake"
"Lola Bunny"
"Catwoman"
"The Chipettes"
"Betty Cooper"
"Wendy Darling"
"Della Duck"
"Daisy Duck"
"Emma Frost"
"Dorothy Gale"
"Jean Grey"
"Veronica Lodge"
"Maleficent"
"Mammy Two Shoes"
"Mother Gothel"
"Minnie Mouse"
"Mystique"
"Olive Oyl"
"Peppermint Patty"
"Jessica Rabbit"
"Sabrina Spellman"
"Storm"
"Venus"
"Wonder Twins"
"X-23"
"Aladdin"
"Archie Andrews"
"King Arthur"
"Baby Huey"
"Bagheera"
"Baloo"
"Barbapapa"
"Bebop and Rocksteady"
"Black Panther"
"Bluto"
"Charlie Brown"
"Dick Dastardly"
"Dr. Heinz Doofenshmirtz"
"Foghorn Leghorn"
"Forky"
"Geppetto"
"Speedy Gonzales"
"Max Goof"
"Goofy"
"The Great Gazoo"
"Grinch"
"Hong Kong Phooey"
"Huey, Dewey, and Louie"
"Jay and Silent Bob"
"Jerry Mouse"
"George Jetson"
"Fred Jones"
"Jughead Jones"
"Krang"
"King Louie"
"Mr. Magoo"
"Marvin the Martian"
"Groot"
"Rocket"
"Link"
"Warner Bros. Cartoons"
"Animaniacs"
"Looney Tunes Cartoons"
"New Looney Tunes"
"Pingu"
"Screen Gems"
"Columbia Pictures"
"The Walt Disney Company"
"Davy Jones"
"Jack Skellington"
"Frog and Toad"
"Hawk and Dove"
"Mermaid Man and Barnacle Boy"
"Pinky and the Brain"
"Plankton and Karen"
"The Rescuers"
"T.O.T.S."
"Timon and Pumbaa"
"Tom and Jerry"
"Tweedledum and Tweedledee"
"Wile E. Coyote and the Road Runner"
"Paramount Pictures"
"Raggedy Ann"
"Fleischer Studios"
"Max Fleischer"
"Hanna-Barbera"
"Muttley"
"Scrappy-Doo"
"Snagglepuss"
"Space Ghost"
"Yogi Bear"
"Aang"
"Adrien Agreste"
"Azula"
"Batman"
"Beavis"
"Toph Beifong"
"Bulma"
"Eric Cartman"
"Velma Dinkley"
"Marinette Dupain-Cheng"
"Doctor Eggman"
"Elmer Fudd"
"Evil Queen"
"Lord Farquaad"
"Finn the Human"
"Princess Fiona"
"Ned Flanders"
"Phineas Flynn"
"Mr. Garrison"
"Gaston"
"Lois Griffin"
"Meg Griffin"
"Peter Griffin"
"Stewie Griffin"
"He-Man"
"Herbert"
"The Hex Girls"
"Captain Hook"
"Iroh"
"Jinx"
"Joker"
"Korra"
"Edna Krabappel"
"Krusty the Clown"
"Troy McClure"
"Edna Mode"
"Alucard"
"Renee Montoya"
"Harley Quinn"
"She-Ra"
"Metro-Goldwyn-Mayer"
"United Artists"
"Droopy"
"Tom Cat"
"Alvin and the Chipmunks"
"The Archies"
"BanG Dream!"
"Dethklok"
"Ensemble Stars!"
"Fat Albert and the Cosby Kids"
"Gorillaz"
"Hi Hi Puffy AmiYumi"
"Jem"
"Josie and the Pussycats"
"K/DA"
"Simpson family"
"Sonic Underground"
"Merida"
"Donkey"
"Puss in Boots"
"Shrek"
"Gumby"
"Mighty Mouse"
"Ub Iwerks"
"Cartoon"
"Universal Pictures"
"Villain"
"Stock character"
"Crime"
"Play"
"Novel"
"Evil"
"Rick Sanchez"
"Warner Bros."
"Tasmanian Devil"
"Werewolf"
"Film"
"Computer animation"
"Stop motion"
"Anti-Venom"
"Captain Atom"
"Cheetah"
"Jonah Hex"
"Lucky Luke"
"Mary Marvel"
"Mister Terrific"
"Negasonic Teenage Warhead"
"Robin"
"Superman in film"
"Morticia Addams"
"Wednesday Addams"
"Talia al Ghul"
"Baroness"
"Birds of Prey"
"Cheryl Blossom"
"Clayface"
"Darna"
"Gomez Addams"
"Pugsley Addams"
"Cobra Commander"
"Wikimedia Commons"
"Black Canary"
"Power Girl"
"Alternative versions of Spider-Man"
"Black people"
"Comics"
"Black Lightning"
"Cyborg"
"Falcon"
"Lucius Fox"
"Miles Morales"
"Monica Rambeau"
"Uncle Ruckus"
"Static"
"War Machine"
"Carl Grimes"
"Cryonics"
"Bucky Barnes"
"Captain America"
"Mr. Freeze"
"Omega Red"
"Red Skull"
"Sailor Moon"
"Spider-Woman"
"Wonder Man"
"Hellboy"
"Nezuko Kamado"
"Tanjiro Kamado"
"Majin Buu"
"Spawn"
"Ryomen Sukuna"
"Calvin and Hobbes"
"Jack Harkness"
"Marceline the Vampire Queen"
"Countryballs"
"Orphan"
"Little Orphan Annie"
"Tarzan"
"Doraemon"
"Superhero"
"Comic book"
"Blue Beetle"
"Leonardo"
"Soldier Boy"
"Teenage Mutant Ninja Turtles"
"Liz Allan"
"Bart Allen"
"Blackfire"
"Donatello"
"Tim Drake"
"Iceman"
"Invincible"
"Michelangelo"
"Kitty Pryde"
"Raphael"
"Snow White"
"Spider-Man"
"Superboy"
"Teen Titans"
"Donna Troy"
"Wally West"
"Twin"
"Booster Gold"
"Captain Britain"
"Captain Marvel"
"John Constantine"
"Jor-El"
"Martian Manhunter"
"Quicksilver"
"Scarlet Witch"
"Skaar"
"Wiccan"
"Professor X"
"Nagato"
"Itachi Uchiha"
"Madara Uchiha"
"Gargamel"
"Trollface"
"Wojak"
"Marvel Comics"
"DC Comics"
"Newspaper"
"Webcomic"
"World Wide Web"
"Media franchise"
"Characters of the DC Extended Universe"
"Characters of the Marvel Cinematic Universe"
"Irene Adler"
"Anna"
"Arwen"
"Lyra Belacqua"
"Elizabeth Bennet"
"Kate Bishop"
"Bo Peep"
"The Bride"
"Foxy Brown"
"Daisy Buchanan"
"Sally Carrera"
"Peggy Carter"
"Sharon Carter"
"Sarah Connor"
"Connie Corleone"
"Mary Corleone"
"Cosette"
"Tia Dalma"
"Carol Danvers"
"Rachel Dawes"
"Blanche DuBois"
"Elphaba"
"Elsa"
"Emmanuelle"
"Enchantress"
"Jyn Erso"
"Esmeralda"
"Katniss Everdeen"
"Fantine"
"Jane Foster"
"Imperator Furiosa"
"Galadriel"
"Gamora"
"Elvira Hancock"
"Miss Havisham"
"Maria Hill"
"Ilsa, She Wolf of the SS"
"Invisible Woman"
"Lady Jessica"
"Bridget Jones"
"Kamala Khan"
"Lois Lane"
"Princess Leia"
"Pippi Longstocking"
"Luna Lovegood"
"M"
"Moira MacTaggert"
"Mantis"
"Beverly Marsh"
"Wanda Maximoff"
"Minerva McGonagall"
"Ali Mills"
"MJ"
"Miss Moneypenny"
"Mon Mothma"
"Mothra"
"Mrs. Doubtfire"
"Nala"
"Admiral Ackbar"
"Cassian Andor"
"Artful Dodger"
"Frodo Baggins"
"Bruce Banner"
"Clint Barton"
"The BFG"
"Jar Jar Binks"
"Jacob Black"
"Sirius Black"
"James Bond"
"Eddie Brock"
"Kyle Broflovski"
"Bumblebee"
"Rhett Butler"
"Lando Calrissian"
"Chef"
"Cheshire Cat"
"Fredo Corleone"
"Sonny Corleone"
"Phil Coulson"
"Edward Cullen"
"Arthur Curry"
"Cyclops"
"Poe Dameron"
"Silvio Dante"
"Mr. Darcy"
"Deadpool"
"Doctor Strange"
"Count Dracula"
"Albus Dumbledore"
"Mike Ehrmantraut"
"Eighth Doctor"
"Uncle Fester"
"Huckleberry Finn"
"Flash Gordon"
"Captain Flint"
"Nick Fury"
"Gambit"
"Samwise Gamgee"
"Jay Gatsby"
"Saw Gerrera"
"Gimli"
"Paulie Gualtieri"
"Forrest Gump"
"Rubeus Hagrid"
"Mickey Haller"
"Hawkeye"
"Greg Heffley"
"Mycroft Holmes"
"Sherlock Holmes"
"Hulk"
"Shinji Ikari"
"Cousin Itt"
"BB-8"
"Chewbacca"
"Jiminy Cricket"
"Fozzie Bear"
"Hermione Granger"
"Doc Holliday"
"Felix Leiter"
"Lost Boys"
"Mini-Me"
"Olaf"
"Piglet"
"R2-D2"
"Marion Ravenwood"
"Sallah"
"Tonto"
"Dr. Watson"
"Ron Weasley"
"Ennis Del Mar"
"Vladimir Harkonnen"
"Trini Kwan"
)


save_root="logs/Alpha_delta"
params="V"
aug_num=10
threshold="1e-1"
delta_coef="0.9"
eta="3"
erase_type="instance"
anchor=" "


root_path="${save_root}"
mkdir -p "$root_path"
config_file="${root_path}/config.txt"

if [ ! -f "$config_file" ]; then
  touch "$config_file"
fi

{
  echo "=============================="
  echo "alpha_delta,加入了sum_hh"
  echo "run_time: $(date '+%Y-%m-%d %H:%M:%S')"
  echo "erase_type: $erase_type"
  echo "params: $params"
  echo "aug_num: $aug_num"
  echo "threshold: $threshold"
  echo "delta_coef: $delta_coef"
  echo "eta: $eta"
  echo "=============================="
} >> "$config_file"




GROUP_SIZE=5
TOTAL=${#instances[@]}
NUM_STEPS=$(( (TOTAL + GROUP_SIZE - 1) / GROUP_SIZE ))

for ((step=0; step<NUM_STEPS; step++)); do
  end=$(( (step + 1) * GROUP_SIZE ))
  group=("${instances[@]:0:end}")

  if [ "${#group[@]}" -eq 0 ]; then
    echo "[INFO] empty group at step ${step}, stopping."
    break
  fi

  targets=$(printf "%s, " "${group[@]}")
  targets=${targets%, }

  step_name=$(printf "step_%03d" "$step")

  echo "[TRAIN] ${step_name}"
  # echo "        total_targets = ${#group[@]}"
  echo "        new_targets   = ${group[@]: -5}"
  # echo "        targets       = ${targets}"


  EXTRA_ARGS=()
  if [ "$step" -gt 0 ]; then
    prev_step=$(printf "step_%03d" "$((step - 1))")
    EXTRA_ARGS+=(--edit_ckpt \
      "${save_root}/${erase_type}/${prev_step}")
  fi

  CUDA_VISIBLE_DEVICES=3 python Alpha_delta.py \
    --target_concepts "$targets" \
    --anchor_concepts "$anchor" \
    --retain_path "data/${erase_type}.csv" \
    --heads "concept" \
    --save_path "${save_root}/${erase_type}/${step_name}" \
    --params "$params" \
    --aug_num "$aug_num" \
    --threshold "$threshold" \
    --delta_coef "$delta_coef" \
    --eta "$eta" \
    "${EXTRA_ARGS[@]}"

done

echo "✅ Done: cumulative erase"
